# Generated by Django 4.2 on 2025-02-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genero_musica',
            field=models.CharField(choices=[('ROCK', 'Rock'), ('POP', 'Pop'), ('RAP', 'Rap'), ('JAZZ', 'Jazz'), ('BLUES', 'Blues'), ('METAL', 'Metal'), ('CLASICA', 'Clasica'), ('ELECTRONICA', 'Electronica'), ('ELECTROSWING', 'Electroswing')], max_length=130),
        ),
    ]
