# Generated by Django 4.2 on 2025-02-08 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album_manager', '0002_alter_album_genero_musica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artista_asociado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='album_manager.artista'),
        ),
    ]
